### PR TITLE
Milestone 3 Project is finished and ready for code review

### PR DESCRIPTION
**Pull request by SafaErden**
game_logic branch is created and all comments from milestone-2 are removed.

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Require changes❌
# 🙋‍♂️ team,
You have done a great a job so far, here are a couple of changes you have to make to get this project approved😎.
* [ ] No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)).
- This is the expected behavior for the game.
* [ ] The application does not allow a player to move into an occupied position
* [ ] The application does not exit due to invalid input - it informs the player about it and asks for their move again
* [ ] The application saves players' move and displays the status of the board after that.
* [ ] The application can determine if the move is a winning move
  * [ ] The application can detect a sequence of three horizontal elements that are equal
  * [ ] The application can detect a sequence of three vertical elements that are equal
  * [ ] The application can detect a sequence of three equal elements in a diagonal from left and right to right
* [ ] The application can tell if there was a draw after players move
* [ ] The application can change active player
> Erden is better to express you commit message in the present tense ie "add" instead of "added"😞
> Guys, I tried to run the game(```ruby bin/main.rb```) but I run into an error🤕

### That is it kindly address these issues and submit another review😷 
#### Happy coding💻
Addo

**Comment by SafaErden** [comment]
The program works after typing ruby bin/main.rb or bin/main.rb

**Comment by SafaErden** [comment]
image

**Comment by SafaErden** [comment]
image

**Comment by SafaErden** [comment]
program inform player for the invalid move and request for a new choice

image

**Comment by SafaErden** [comment]
the program shows the scoreboard after each game

image

**Comment by SafaErden** [comment]
it displays the status of the board after each valid move

**Comment by SafaErden** [comment]
it detects the winning sequence and informs the players
image

**Comment by SafaErden** [comment]
after each move, it changes the active player
image

**Comment by SafaErden** [comment]
it informs players if there is a draw

image

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hello Team 👋

You've both done well on this milestone.

However as stated in the Partwright requirements the game is expected to have at least two classes, but yours has only one. Kindly add more classes to yours.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

Once more great job on this.🚀

Kindly fix this issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Review by Torres-ssf — APPROVED** [review]
### Project Approved :clap: :clap: :clap: 
Hi there team :hand: 
Great job implementing the requested changes.
I must say, I liked your game, I can see that you put a lot of attention in the details. :+1: 
**Your project it's approved** 
Good luck in the next one.

Happy coding :computer: 
**Sergio Torres**

**Pull request merged**
